// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RcppTest3_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nested_loops
NumericMatrix rcpp_nested_loops(const NumericMatrix& x, const IntegerMatrix& y);
RcppExport SEXP _RcppTest3_rcpp_nested_loops(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nested_loops(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_nested_loops
NumericMatrix rcpp_parallel_nested_loops(const NumericMatrix& x, const IntegerMatrix& y);
RcppExport SEXP _RcppTest3_rcpp_parallel_nested_loops(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_nested_loops(x, y));
    return rcpp_result_gen;
END_RCPP
}
