# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RcppTest3_rcpp_hello_world`)
}

rcpp_nested_loops <- function(x, y) {
    .Call(`_RcppTest3_rcpp_nested_loops`, x, y)
}

rcpp_parallel_nested_loops <- function(x, y) {
    .Call(`_RcppTest3_rcpp_parallel_nested_loops`, x, y)
}

